server:
  port: 8083
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: self-service


  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: self-service
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG