<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://mobileoperator.com/base"
           elementFormDefault="qualified">

    <!-- Общие типы -->
    <xs:simpleType name="uuidType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-fA-F\-]{36}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="phoneNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+380[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>